name: Testing
 
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"      

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3, 8.4]

    name: Testing PHP${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Setup Certificates
        run: |
            mkdir -p ./scripts
            mkdir -p ./config/certificates/testing

            for i in 1 2 3; do
              NIP="666966692$i"
              VAR_NAME="SIGNATURE_NIP_$i"
              echo "${!VAR_NAME}" > ./scripts/signature-nip.txt

              mkdir -p "./config/certificates/testing/$NIP"

              openssl req -newkey rsa:2048 -nodes \
                -keyout "./config/certificates/testing/$NIP/key.pem" \
                -out "./config/certificates/testing/$NIP/certificate.csr" \
                -config ./scripts/signature-nip.txt

              openssl x509 -req \
                -in "./config/certificates/testing/$NIP/certificate.csr" \
                -signkey "./config/certificates/testing/$NIP/key.pem" \
                -out "./config/certificates/testing/$NIP/certificate.crt"

              openssl pkcs12 -export \
                -out "./config/certificates/testing/$NIP/certificate.p12" \
                -inkey "./config/certificates/testing/$NIP/key.pem" \
                -in "./config/certificates/testing/$NIP/certificate.crt" \
                -passout pass:password
            done
        env:
          SIGNATURE_NIP_1: ${{ vars.SIGNATURE_NIP_1 }}
          SIGNATURE_NIP_2: ${{ vars.SIGNATURE_NIP_2 }}
          SIGNATURE_NIP_3: ${{ vars.SIGNATURE_NIP_3 }}    

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader

      - name: Run CS Fixer
        if: matrix.php == '8.1'
        run: ./vendor/bin/php-cs-fixer fix --dry-run --allow-unsupported-php-version=yes

      - name: Run Rector
        if: matrix.php == '8.1'
        run: ./vendor/bin/rector process --dry-run

      - name: Run PHPStan
        if: matrix.php == '8.1'
        run: ./vendor/bin/phpstan analyse --error-format=github 

      - name: Run Pest Unit tests
        run: ./vendor/bin/pest tests/Unit --parallel --ci

      - name: Run Pest Feature tests
        if: matrix.php == '8.1'
        run: ./vendor/bin/pest tests/Feature --parallel --ci